### ISSUE TITLE
incomplete datasets in curated area

### ISSUE THREAD

**Issue by JaimePrilusky** [CellMigStandOrg/CMSO-datasets#10]
CMSO-datasets available at https://github.com/CellMigStandOrg/CMSO-datasets are not complete nor serve as a clean example of how a dataset should look like. Too many mandatory fields are empty.

**Comment by simleo** [comment]
@JaimePrilusky can you point to concrete examples and suggest how to fix them?

**Comment by pcmasuzzo** [comment]
@JaimePrilusky - maybe a PR would be better.

**Comment by JaimePrilusky** [comment]
For example, on cmsodataset0002, mandatory fields like Investigation and Study are empty. The 'Study Protocol Parameters' section looks strange.
